In [1]:
import numpy as np

In [4]:
a = np.random.normal(size=2)
print(a)
print(a.shape)
b = np.random.normal(size = 3)
print(b)
print(b.shape)

[-0.52258678  1.51746681]
(2,)
[ 2.31640558  0.55012831 -0.1344389 ]
(3,)


In [9]:
a

array([-0.52258678,  1.51746681])

In [10]:
b

array([ 2.31640558,  0.55012831, -0.1344389 ])

In [7]:
b[:,None]

array([[ 2.31640558],
       [ 0.55012831],
       [-0.1344389 ]])

In [11]:
a*b[:,None]

array([[-1.21052293,  3.51506857],
       [-0.28748978,  0.83480146],
       [ 0.07025599, -0.20400657]])