In [1]:
import numpy as np

In [8]:
cc = np.random.randint(0,1)

cc

0

In [9]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [7]:
cc.shape

(10,)

In [2]:
a = np.random.normal(size=2)
print(a)
print(a.shape)
b = np.random.normal(size = 3)
print(b)
print(b.shape)

[ 0.41405314 -0.53705718]
(2,)
[1.2322509  2.05189188 1.48746255]
(3,)


In [3]:
a

array([ 0.41405314, -0.53705718])

In [4]:
b

array([1.2322509 , 2.05189188, 1.48746255])

In [5]:
b[:,None]

array([[1.2322509 ],
       [2.05189188],
       [1.48746255]])

In [6]:
b[:,None].shape

(3, 1)

In [7]:
a*b[:,None]

array([[ 0.51021736, -0.66178919],
       [ 0.84959229, -1.10198327],
       [ 0.61588854, -0.79885244]])

In [8]:
c = np.random.normal(size=2)
c

array([ 0.7636477 , -0.39620527])

In [9]:
np.dot(a,c)

0.5289756162294985

In [10]:
d = np.random.normal(size = [2,3])
d

array([[-0.94627701, -0.31744691,  0.08365969],
       [ 0.3159518 , -1.19743653, -0.23504015]])

In [11]:
np.dot(a,d)

array([-0.56149315,  0.511652  ,  0.16086956])

In [19]:
aa = np.random.randint(0,6,size=(3,4,8))
aa

array([[[5, 4, 1, 2, 3, 0, 5, 1],
        [3, 5, 3, 1, 4, 3, 4, 0],
        [4, 0, 5, 2, 3, 3, 0, 2],
        [2, 2, 3, 0, 5, 5, 4, 3]],

       [[4, 5, 4, 3, 1, 3, 0, 5],
        [3, 4, 1, 5, 1, 3, 1, 1],
        [1, 2, 2, 2, 1, 3, 4, 4],
        [2, 1, 1, 1, 5, 5, 0, 3]],

       [[0, 2, 4, 2, 1, 4, 0, 5],
        [2, 4, 3, 0, 1, 2, 0, 1],
        [3, 4, 5, 1, 5, 4, 1, 4],
        [3, 3, 4, 2, 3, 5, 1, 4]]])

In [18]:
np.max(aa,axis=(1,2))

array([5, 5, 5])

In [20]:
test_shape = (np.random.choice(range(3)), 4, 5, 6)
test_numbers = np.random.choice(range(256), test_shape)
test_numbers

array([[[[  8,  29, 201, 109,  42, 127],
         [233, 112, 162, 199, 187,  19],
         [156,   0, 211,  33, 242, 229],
         [ 96,  36, 248, 225,  47, 206],
         [ 25, 170, 134,  54, 212, 241]],

        [[230, 206,  14, 124,  74,  76],
         [ 23,  67, 140,  19, 181, 214],
         [206,   8, 237,  59, 109,  48],
         [100, 139, 213,  23,  21, 230],
         [155,  53, 128,  38,  17, 226]],

        [[145,  75,  33,  17, 121, 113],
         [126, 184, 225,  44, 173,   3],
         [241,  16, 218,   4, 115, 104],
         [ 31, 157, 137,  40, 167, 221],
         [ 44,  34, 243,  71, 133,  66]],

        [[ 27,   7, 214, 230,  90,  68],
         [109,  99, 105, 167,  75, 211],
         [  6,  10, 137, 152, 114, 234],
         [ 81, 219, 145,  39,  69,  76],
         [173, 122, 237, 237, 140, 190]]],


       [[[145,  91,  80, 131, 212, 176],
         [106, 198, 252, 196, 246,  77],
         [237,  33, 196,   4, 164, 153],
         [187,  63, 203, 178, 116, 193],
      