In [1]:
import numpy as np

In [2]:
a = np.random.normal(size=2)
print(a)
print(a.shape)
b = np.random.normal(size = 3)
print(b)
print(b.shape)

[ 0.41405314 -0.53705718]
(2,)
[1.2322509  2.05189188 1.48746255]
(3,)


In [3]:
a

array([ 0.41405314, -0.53705718])

In [4]:
b

array([1.2322509 , 2.05189188, 1.48746255])

In [5]:
b[:,None]

array([[1.2322509 ],
       [2.05189188],
       [1.48746255]])

In [6]:
b[:,None].shape

(3, 1)

In [7]:
a*b[:,None]

array([[ 0.51021736, -0.66178919],
       [ 0.84959229, -1.10198327],
       [ 0.61588854, -0.79885244]])

In [8]:
c = np.random.normal(size=2)
c

array([ 0.7636477 , -0.39620527])

In [9]:
np.dot(a,c)

0.5289756162294985

In [10]:
d = np.random.normal(size = [2,3])
d

array([[-0.94627701, -0.31744691,  0.08365969],
       [ 0.3159518 , -1.19743653, -0.23504015]])

In [11]:
np.dot(a,d)

array([-0.56149315,  0.511652  ,  0.16086956])