In [1]:
import numpy as np

In [2]:
a = np.random.normal(size=2)
print(a)
print(a.shape)
b = np.random.normal(size = 3)
print(b)
print(b.shape)

[ 1.72340463 -0.81084599]
(2,)
[-0.21248409 -0.47499912 -0.61567567]
(3,)


In [3]:
a

array([ 1.72340463, -0.81084599])

In [4]:
b

array([-0.21248409, -0.47499912, -0.61567567])

In [5]:
b[:,None]

array([[-0.21248409],
       [-0.47499912],
       [-0.61567567]])

In [7]:
b[:,None].shape

(3, 1)

In [6]:
a*b[:,None]

array([[-0.36619607,  0.17229188],
       [-0.81861568,  0.38515113],
       [-1.0610583 ,  0.49921815]])

In [8]:
c = np.random.normal(size=2)
c

array([ 0.04038603, -0.06236023])

In [9]:
np.dot(a,c)

0.12016601562851068